# Generated by Django 4.2.14 on 2025-08-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
    ]
